### ISSUE TITLE
Override default sublime_text_packages

### ISSUE THREAD

**Issue by djallits** [kitchenplan/chef-applications#114]
I can successfully add new packages, but how do I escape installing items like `Theme - Flatland`?

**Comment by roderik** [comment]
Does overriding it in your config work? 
https://github.com/roderik/kitchenplan-config/blob/master/config/people/roderik.yml

**Comment by djallits** [comment]
No, but I am going to close this for now, as I feel this is an configuration issue generated by me and not by Kitchenplan itself.
